<select name="Macro" id="Macro" required readonly>
    <?php switch ($XMLdata->day_title[$index]->job[$indexJob]->macro)
    {
        case "V10":
            echo "<option value=\"V10\" selected>&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VDE":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\" selected>&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VES":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\" selected>&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VSW":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\" selected>&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VFR":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\" selected>&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VBE":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\" selected>&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VHK":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\" selected>&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VAU":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\" selected>&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VNE":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\" selected>&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VPT":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\" selected>&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VUK":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\" selected>&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VCH":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\" selected>&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VSL":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\" selected>&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VGE":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\" selected>&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VAF":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\" selected>&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VMX":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\" selected>&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VHE":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\" selected>&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VYA":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\" selected>&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\">&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        case "VUM":
            echo "<option value=\"V10\">&nbsp Italia V10&nbsp&nbsp</option><option value=\"VDE\">&nbsp Germania VDE&nbsp&nbsp</option><option value=\"VES\">&nbsp Spagna VES&nbsp&nbsp</option><option value=\"VSW\">&nbsp Svezia VSW&nbsp&nbsp</option><option value=\"VFR\">&nbsp Francia VFR&nbsp&nbsp</option><option value=\"VBE\">&nbsp Belgio VBE&nbsp&nbsp</option><option value=\"VHK\">&nbsp Hong Kong VHK&nbsp&nbsp</option><option value=\"VAU\">&nbsp Austria VAU&nbsp&nbsp</option><option value=\"VNE\">&nbsp Olanda VNE&nbsp&nbsp</option><option value=\"VPT\">&nbsp Portogallo VPT&nbsp&nbsp</option><option value=\"VUK\">&nbsp Inghilterra VUK&nbsp&nbsp</option><option value=\"VCH\">&nbsp Svizzera VCH&nbsp&nbsp</option><option value=\"VSL\">&nbsp Slovenia VSL&nbsp&nbsp</option><option value=\"VGE\">&nbsp Est Europa VGE&nbsp&nbsp </option><option value=\"VAF\">&nbsp Sud Africa VAF&nbsp&nbsp</option><option value=\"VMX\">&nbsp Messico VMX&nbsp&nbsp</option><option value=\"VHE\">&nbsp Grecia VHE&nbsp&nbsp</option><option value=\"VYA\">&nbsp Dubai VYA&nbsp&nbsp</option><option value=\"VUM\" selected>&nbsp Miami VUM&nbsp&nbsp</option>";
            break;
        
        
    }
        
    ?>
    
</select>